spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080